# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "server.Company" do
    optional :id, :int64, 1
    optional :name, :string, 2
  end
  add_message "server.Transaction" do
    optional :id, :string, 1
    optional :amount, :double, 2
  end
  add_message "server.User" do
    optional :username, :string, 1
  end
  add_message "server.Order" do
    optional :id, :int64, 1
  end
  add_message "server.Calculation" do
    optional :id, :int64, 1
  end
  add_message "server.NewTransaction" do
    optional :env, :enum, 1, "server.NewTransaction.Env"
    optional :company, :message, 2, "server.Company"
    optional :transaction, :message, 3, "server.Transaction"
    optional :user, :message, 4, "server.User"
    optional :order, :message, 5, "server.Order"
    optional :calculation, :message, 6, "server.Calculation"
  end
  add_enum "server.NewTransaction.Env" do
    value :IL, 0
    value :RU, 1
    value :UK, 2
  end
  add_message "server.Empty" do
  end
end

module Server
  Company = Google::Protobuf::DescriptorPool.generated_pool.lookup("server.Company").msgclass
  Transaction = Google::Protobuf::DescriptorPool.generated_pool.lookup("server.Transaction").msgclass
  User = Google::Protobuf::DescriptorPool.generated_pool.lookup("server.User").msgclass
  Order = Google::Protobuf::DescriptorPool.generated_pool.lookup("server.Order").msgclass
  Calculation = Google::Protobuf::DescriptorPool.generated_pool.lookup("server.Calculation").msgclass
  NewTransaction = Google::Protobuf::DescriptorPool.generated_pool.lookup("server.NewTransaction").msgclass
  NewTransaction::Env = Google::Protobuf::DescriptorPool.generated_pool.lookup("server.NewTransaction.Env").enummodule
  Empty = Google::Protobuf::DescriptorPool.generated_pool.lookup("server.Empty").msgclass
end
