# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: server.proto for package 'server'

require 'grpc'
require 'server_pb'

module Server
  module Transactions
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'server.Transactions'

      rpc :Add, NewTransaction, Empty
    end

    Stub = Service.rpc_stub_class
  end
end
